### ISSUE TITLE
Can you share your running requirements of python packages ?

### ISSUE THREAD

**Issue by zide05** [tagoyal/dae-factuality#2]
Also, i'd like to ask if the result of test data in resources/summary_pairs.json corresponding to DAE Reranking Acc in table 4 ?

**Comment by tagoyal** [comment]
Yes, the results in Table 4 are computed on the summarization pairs in resources/summary_pairs.json

I've included environment details etc. in the github repo now, thanks for pointing this out! Also included a requirements file.
